name: build iso

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker env
      run: docker build . -t bill-buildenv

    - name: List files and permissions
      run: |
       ls -l
       chmod +x build.sh

    - name: Build iso
      run: |
        docker run --rm -v "$(pwd):/root/env" bill-buildenv build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: "BILL-barebones"
          path: "."
